export const POKEMONS_LOADING = 'POKEMONS_LOADING';
export const POKEMONS_FAILED = 'POKEMONS_FAILED';
export const ADD_POKEMONS = 'ADD_POKEMONS';

export const POKEMON_LOADING = 'POKEMON_LOADING';
export const POKEMON_FAILED = 'POKEMON_FAILED';
export const ADD_POKEMON = 'ADD_POKEMON';

export const POKEMON_TYPES_LOADING = 'POKEMON_TYPES_LOADING';
export const POKEMON_TYPES_FAILED = 'POKEMON_TYPES_FAILED';
export const ADD_POKEMON_TYPES = 'ADD_POKEMON_TYPES';

export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const UNFAVORITE_POKEMON_FAILD = 'UNFAVORITE_POKEMON_FAILD';
export const UNFAVORITE_POKEMON_SUCCESS = 'UNFAVORITE_POKEMON_SUCCESS';
export const FAVORITE_POKEMON_FAILD = 'FAVORITE_POKEMON_FAILD';
export const FAVORITE_POKEMON_SUCCESS = 'FAVORITE_POKEMON_SUCCESS';

export const OPTIMISTIC_POKEMON = 'OPTIMISTIC_POKEMON';